### ISSUE TITLE
Building 9f8516c fails with: mem.c:295:32: error: ‘PLIST_DFT_HASHSIZE’ undeclared

### ISSUE THREAD

**Issue by nikkej** [phorward/unicc#19]
Building commit [9f8516c](https://github.com/phorward/unicc/commit/9f8516c76fb65ac26b6900617ea5aa19ecca1228) gives:
mem.c: In function ‘create_item’:
mem.c:295:32: error: ‘PLIST_DFT_HASHSIZE’ undeclared (first use in this function)
  295 |  plist_init( &i->lookahead, 0, PLIST_DFT_HASHSIZE, PLIST_MOD_PTR );
      |                                ^~~~~~~~~~~~~~~~~~

And I checked, declaration of PLIST_DFT_HASHSIZE is missing (removed from phorward.h in commit 9af588682596a9e846dcdaa0ca33d54131c7f913 of libphorward)

**Comment by phorward** [comment]
Hi @nikkej, thank you for filing this issue. I know about this problem, since libphorward was released in v1.0, it is not compatible to the current unicc master. You need [v0.24 of libphorward](https://github.com/phorward/phorward/releases/tag/v0.24.0) to compile. 

Alternatively, you can check out the [develop branch of unicc](https://github.com/phorward/unicc/tree/develop). It is self-contained and has no further dependencies, because the libphorward was integrated into the unicc repo to make building simpler and resolve this version dependency problem. The develop branch is planned as v1.7 coming with a new parser template which is currently under development.

I hope this helps!

**Comment by nikkej** [comment]
@phorward, sorry it took some time for me to reply. Since UniCC is new thing for me I have been busy reading your excellent book about UniCC. Thank you about the hints for correct versions.
