### ISSUE TITLE
More details on precedence to resolve parser conflicts

### ISSUE THREAD

**Issue by mingodad** [phorward/unicc#25]
Comparing `yacc/bison` and `lemon` on how they use rule precedence to resolve grammar conflicts they differ on how to do it as show bellow:

- YACC/BISON when not specified with `%prec` will use the precedence assigned (if any) to the **last terminal** on the rule.
- LEMON when not specified with `[prec]` will use  the precedence assigned to the **first terminal** on the rule **that has precedence assigned**.
- UNICC ?

Can this have a bit of explanation ?

**Comment by mingodad** [comment]
Also lemon uses rule precedence to resolve reduce/reduce conflicts.

**Comment by phorward** [comment]
Hello @mingodad, thank you for asking.

In unicc, the precedence of a production is resolved similarly to yacc: The precedence of the rightmost symbol with a precedence setting will be used. Instead of only terminal symbols, unicc also uses the precedence settings of nonterminal symbols.

The corresponding position in the code is [here](https://github.com/phorward/unicc/blob/master/src/rewrite.c#L418). unicc2 has the corresponding algorithm [here](https://github.com/phorward/unicc/blob/unicc2/grammar.c#L942).

**Comment by mingodad** [comment]
Thank you for reply !
Looking through the code you've pointed out it seems that this comment is misleading https://github.com/phorward/unicc/blob/85ec57b3edeb6fe79cf0dbe7fc93def3928413c5/src/rewrite.c#L425 because it's using the same procedure as the next loop to look for the **rightmost** .

**Comment by phorward** [comment]
You're right, the comment is wrong here.
