### ISSUE TITLE
Lexer state

### ISSUE THREAD

**Issue by wwall** [phorward/unicc#6]
I need do some lexer state (in flex it declare in <state>)
How i can declare it in UniCC?

**Comment by phorward** [comment]
Hello @wwall,
I'm not sure if I'm able to correctly answer your question, because 'm not sure what you exactly mean with the 'lexer state'.
 
Generally, the lexer states are generated by UniCC itself, so no lexer states must be declared explicitly. You can intervene into the lexical analysis with custom semantic actions, as described in the [user's manual](https://www.phorward-software.com/products/unicc/unicc.pdf) in section 4.4.1.3.1 (page 75).

UniCC does not provides an easy way to connect it to an externally declared lexer, yet. This would be a good point to be featured in [UniCCv2](https://github.com/phorward/unicc/wiki/UniCC-v2). 

I hope this helps you a little bit more with your question.
